#!/bin/sh

# Usage: mr update
# Summary: Update 'mr' cli tool from git.
# Help: Selfupdate which pulls from the repo on github.
#

set -e

echo "Updating mill in "$_MILL_ROOT" ..."
cd $_MILL_ROOT
git pull -q origin master \
&& echo "SUCCESS" \
|| echo "FAIL"